### ISSUE TITLE
Handling django rest framework?

### ISSUE THREAD

**Issue by Ikszad** [mkdocstrings/mkdocstrings#141]
Hello!
I tried using mkdocstrings in my project, but unfortunately, it crashes when meeting the drf package.
Mkdocs and mkdocstrings are installed in my poetry virtual environment (as well as rest of the packages)
Here is my mkdocs.yml.
```
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - "import os"
            - "import sys"
            - "import django"
            - "sys.path.insert(0, os.path.abspath('..'))"
            - "os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'settings.development')"
            - "django.setup()"
```

When I want to document a simple ModelViewSet
```
class SomeModelViewSet(viewsets.ModelViewSet):
    serializer_class =SomeSerializer
```

I encounter an error in the serializer
```
class SomeSerializer(serializers.ModelSerializer):
    some_field = serializers.CharField(source="source")
```
Error message
mkdocstrings.handlers.CollectionError: 'some_field' object has no attribute 'metadata'

Is it me doing something wrong or just support for drf just is not there?

**Comment by pawamoy** [comment]
We do not officially support Django Rest Framework, however we could consider this a bug in `pytkdocs` and investigate to fix it :slightly_smiling_face: 

Do you have a repo you can share so I can reproduce?

**Comment by Ikszad** [comment]
Good to hear. :) Unfortunately, I can't share the repo, this occurred in a commercial project. I can probably create one, but can't tell when, as I am pretty busy.

**Comment by n2ygk** [comment]
@pawamoy this demonstrates the error: https://github.com/columbia-it/django-jsonapi-training/blob/pytkdocs_error/test_pytkdocs.py

```
(env) django-jsonapi-training$ python test_pytkdocs.py
Traceback (most recent call last):
  File "test_pytkdocs.py", line 23, in <module>
    print(process_config(json.loads(input)))
  File "/Users/alan/src/django-training/env/lib/python3.8/site-packages/pytkdocs/cli.py", line 91, in process_config
    obj = loader.get_object_documentation(path, members)
  File "/Users/alan/src/django-training/env/lib/python3.8/site-packages/pytkdocs/loader.py", line 342, in get_object_documentation
    root_object = self.get_class_documentation(leaf, members)
  File "/Users/alan/src/django-training/env/lib/python3.8/site-packages/pytkdocs/loader.py", line 494, in get_class_documentation
    self.add_fields(
  File "/Users/alan/src/django-training/env/lib/python3.8/site-packages/pytkdocs/loader.py", line 516, in add_fields
    root_object.add_child(add_method(child_node))
  File "/Users/alan/src/django-training/env/lib/python3.8/site-packages/pytkdocs/loader.py", line 645, in get_marshmallow_field_documentation
    docstring=prop.metadata.get("description"),
AttributeError: 'ManyRelatedField' object has no attribute 'metadata'
```

**Comment by pawamoy** [comment]
So it seems Django/DRF fields are detected as Marshmallow fields, when they should not. I'll therefore mark this as a bug instead of a feature request, because even if we don't fully support Django/DRF, pytkdocs should not crash while loading the docs.

**Comment by n2ygk** [comment]
> So it seems Django/DRF fields are detected as Marshmallow fields, when they should not. I'll therefore mark this as a bug instead of a feature request, because even if we don't fully support Django/DRF, pytkdocs should not crash while loading the docs.

It would be greatly appreciated if DRF were supported! Happy to try and submit a PR if you can provide me some guidance.

**Comment by gabriel-v** [comment]
> So it seems Django/DRF fields are detected as Marshmallow fields, when they should not.

So a simple workaround is getting rid of the Marshmallow field detector method in the `setup_commands`:

```python
from unittest.mock import MagicMock
import pytkdocs.loader
pytkdocs.loader.Loader.get_marshmallow_field_documentation = lambda *x, **y: MagicMock()
```

Tested on ` pytkdocs==0.11.0` for my limited DRF usage

**Comment by johnthagen** [comment]
Here is another stacktrace showing this happening on a DRF application:

```
ERROR    -  mkdocstrings.extension: 'FloatField' object has no attribute 'metadata'
Traceback (most recent call last):
  File ".tox/docs-serve/lib/python3.9/site-packages/pytkdocs/cli.py", line 205, in main
    output = json.dumps(process_json(line))
  File ".tox/docs-serve/lib/python3.9/site-packages/pytkdocs/cli.py", line 114, in process_json
    return process_config(json.loads(json_input))
  File ".tox/docs-serve/lib/python3.9/site-packages/pytkdocs/cli.py", line 91, in process_config
    obj = loader.get_object_documentation(path, members)
  File ".tox/docs-serve/lib/python3.9/site-packages/pytkdocs/loader.py", line 358, in get_object_documentation
    root_object = self.get_module_documentation(leaf, members)
  File ".tox/docs-serve/lib/python3.9/site-packages/pytkdocs/loader.py", line 436, in get_module_documentation
    root_object.add_child(self.get_module_documentation(leaf))
  File ".tox/docs-serve/lib/python3.9/site-packages/pytkdocs/loader.py", line 426, in get_module_documentation
    root_object.add_child(self.get_class_documentation(child_node))
  File ".tox/docs-serve/lib/python3.9/site-packages/pytkdocs/loader.py", line 531, in get_class_documentation
    self.add_fields(
  File ".tox/docs-serve/lib/python3.9/site-packages/pytkdocs/loader.py", line 599, in add_fields
    root_object.add_child(add_method(child_node))
  File ".tox/docs-serve/lib/python3.9/site-packages/pytkdocs/loader.py", line 761, in get_marshmallow_field_documentation
    docstring=prop.metadata.get("description"),
AttributeError: 'FloatField' object has no attribute 'metadata'
```

**Comment by mschoettle** [comment]
> > So it seems Django/DRF fields are detected as Marshmallow fields, when they should not.
> 
> So a simple workaround is getting rid of the Marshmallow field detector method in the `setup_commands`:
> 
> ```python
> from unittest.mock import MagicMock
> import pytkdocs.loader
> pytkdocs.loader.Loader.detect_field_model = lambda *x, **y: False
> pytkdocs.loader.Loader.get_marshmallow_field_documentation = lambda *x, **y: MagicMock()
> ```
> 
> Tested on ` pytkdocs==0.11.0` for my limited DRF usage

Thanks @gabriel-v. I tried it out but unfortunately it causes 

```python
ERROR    -  mkdocstrings.extension: Error while loading JSON:

            Traceback (most recent call last):
              File "/usr/local/lib/python3.9/site-packages/mkdocstrings/handlers/python.py", line 251, in collect
                result = json.loads(stdout)
              File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
                return _default_decoder.decode(s)
              File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
              File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
                raise JSONDecodeError("Expecting value", s, err.value) from None
            json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The string it is trying to decode as JSON is:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'module' object is not callable
```

Do you have a full working example?

**Comment by gabriel-v** [comment]
> Do you have a full working example?

@mschoettle Sure thing:
- mocking code [here](https://github.com/liquidinvestigations/hoover-snoop2/blob/600f9ae4aed16aa17d2f9a7b428dba1443e131b8/docs/docs_mock.py#L51)
- mocking modules and functions/classes listed in [this file](https://github.com/liquidinvestigations/hoover-snoop2/blob/600f9ae4aed16aa17d2f9a7b428dba1443e131b8/docs/mock-modules.txt) -- you need to list every single module, class, function you import directly or indirectly in your code, but you don't install when building docs
- exact [package versions](https://github.com/liquidinvestigations/hoover-snoop2/blob/600f9ae4aed16aa17d2f9a7b428dba1443e131b8/docs/requirements-mkdocs.txt) -- probably as old as this issue, maybe downgrade?

I remember getting JSONDecodeErrors from this library. You get `None` instead of JSON if you mock out a module/function and then later call that code from the documentation builder. Keep digging in PDB for the stack trace above your `TypeError: 'module' object is not callable` and you should find out what module it's talking about.

**Comment by mschoettle** [comment]
Thanks a lot, @gabriel-v! I had briefly looked at your repos to see if I can find where you used it but missed that one.

That was very helpful and also gave me some additional ideas.
I was able to generate the reference for my code base with just 

```python
import pytkdocs.loader
pytkdocs.loader.Loader.get_marshmallow_field_documentation = lambda *x, **y: MagicMock()
```

`pytkdocs.loader.Loader.detect_field_model = lambda *x, **y: False` is helpful if one wants to omit listing the model fields.

And I can confirm that this works with the latest versions (mkdocs v1.2.3, mkdocstrings v0.17.0 and pytkdocs v0.15.0).

**Comment by pawamoy** [comment]
Hello everyone! The [new handler](https://mkdocstrings.github.io/handlers/overview/#about-the-python-handlers) is able to visit the code using its AST instead of executing and introspecting it. I believe this would solve all these `AttributeError` and the like. I'd greatly appreciate if some of you could beta-test the new handler on Django/DRF projects and report back here :slightly_smiling_face:

**Comment by n2ygk** [comment]
> Hello everyone! The [new handler](https://mkdocstrings.github.io/handlers/overview/#about-the-python-handlers) is able to visit the code using its AST instead of executing and introspecting it. I believe this would solve all these `AttributeError` and the like. I'd greatly appreciate if some of you could beta-test the new handler on Django/DRF projects and report back here 🙂

Am I doing it right?
```
(venv) django-jsonapi-training$ pip freeze | grep mkdo
mkdocs==1.2.3
mkdocs-autorefs==0.3.1
mkdocstrings==0.18.0
mkdocstrings-python==0.5.2
mkdocstrings-python-legacy==0.2.1
(venv) django-jsonapi-training$ more test_pytkdocs.py 
import os
import sys
import json
import django
from pytkdocs.cli import process_config

# reproduce "AttributeError: 'ManyRelatedField' object has no attribute 'metadata'"

input = """{
  "objects": [
    {
      "path": "myapp.serializers.CourseSerializer",
      "filters": [
        "!^_[^_]"
      ]
    }
  ]
}
"""

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "training.settings")
django.setup()
print(process_config(json.loads(input)))
(venv) django-jsonapi-training$ python test_pytkdocs.py 
Traceback (most recent call last):
  File "/Users/ac45/src/django-jsonapi-training/test_pytkdocs.py", line 23, in <module>
    print(process_config(json.loads(input)))
  File "/Users/ac45/src/django-jsonapi-training/venv/lib/python3.9/site-packages/pytkdocs/cli.py", line 91, in process_config
    obj = loader.get_object_documentation(path, members)
  File "/Users/ac45/src/django-jsonapi-training/venv/lib/python3.9/site-packages/pytkdocs/loader.py", line 360, in get_object_documentation
    root_object = self.get_class_documentation(leaf, members)
  File "/Users/ac45/src/django-jsonapi-training/venv/lib/python3.9/site-packages/pytkdocs/loader.py", line 544, in get_class_documentation
    self.add_fields(
  File "/Users/ac45/src/django-jsonapi-training/venv/lib/python3.9/site-packages/pytkdocs/loader.py", line 612, in add_fields
    root_object.add_child(add_method(child_node))
  File "/Users/ac45/src/django-jsonapi-training/venv/lib/python3.9/site-packages/pytkdocs/loader.py", line 782, in get_marshmallow_field_documentation
    docstring=prop.metadata.get("description"),
AttributeError: 'ManyRelatedField' object has no attribute 'metadata'
```

**Comment by pawamoy** [comment]
Hi @n2ygk, not exactly, pytkdocs is not used by the new handler, [Griffe](https://github.com/mkdocstrings/griffe) is.

**Comment by n2ygk** [comment]
> Hi @n2ygk, not exactly, pytkdocs is not used by the new handler, [Griffe](https://github.com/mkdocstrings/griffe) is.

Well that's good. It means it's probably fixed and I just need to remember how I tried to do this way back when ;-)

**Comment by mschoettle** [comment]
> Hello everyone! The [new handler](https://mkdocstrings.github.io/handlers/overview/#about-the-python-handlers) is able to visit the code using its AST instead of executing and introspecting it. I believe this would solve all these `AttributeError` and the like. I'd greatly appreciate if some of you could beta-test the new handler on Django/DRF projects and report back here 🙂

Hi @pawamoy, thanks a lot! I just tried it on a small code base and I can confirm that the errors disappeared. One notable difference is that the Django support is gone (the additional Django-specific labels are not there anymore, also the Django model fields are gone).

And a general thing is that superclasses etc. show the complete qualified name on hover with the legacy handler.

Lastly, would this new handler/`griffe` be able to extract comments on constants that are above the declaration and prefixed with `#:`?

If there is anything else I can test let me know please.

**Comment by pawamoy** [comment]
> I just tried it on a small code base and I can confirm that the errors disappeared

Thanks a lot for testing!

> the Django support is gone (the additional Django-specific labels are not there anymore, also the Django model fields are not showing anymore).

Yes, for now there's no "Django extension" so no corresponding labels, but this will be added back (soon I hope).
About model fields not showing up, could you share a snippet so I can replicate/investigate?

> show the complete qualified name on hover with the legacy handler which is not the case anymore

I've noticed it myself indeed. Thanks for reporting.

> creating a feature request to make it possible to link to the documentation of the types which I think should be possible using the objects.inv files

When griffe works fine, this should already happen :slightly_smiling_face: You can [import Django's inventory](https://mkdocstrings.github.io/usage/#cross-references-to-other-projects-inventories) and links to Django's doc will be automatically added.

> would this new handler/griffe be able to extract comments on constants that are above the declaration and prefixed with #:?

We're using `ast` directly, and support for type comments was only added in Python 3.8, so when Python 3.7 is EOL, maybe. Or we could use `tokenize` on Python 3.7 (we already do to get the ending line numbers). It's honestly not a priority to me, because I use type annotations, but if someone wants to send a PR to Griffe, I'll review it.

> When install mkdocstrings-python it also installs the legacy handler and pytkdocs

Yes, that's normal, it's just a transition period. Next version of mkdocstrings will stop always installing the legacy handler and pytkdocs.

---

Thanks again for the feedback. I'll open corresponding issues to keep track of each item.

**Comment by pawamoy** [comment]
- Full path on cross-refs is restored.
- Model fields not showing up makes sense: previously their docstring would be fetched from their description or help text. The new handler does not have this special handling. But I'm prototyping a Django extension :slightly_smiling_face:

**Comment by johnthagen** [comment]
I can confirm that with `mkdocstrings[python]==0.18.0` I no long am receiving errors during the build on a DRF application.

**Comment by mschoettle** [comment]
Thanks for your detailed response!

> > would this new handler/griffe be able to extract comments on constants that are above the declaration and prefixed with #:?
> 
> We're using `ast` directly, and support for type comments was only added in Python 3.8, so when Python 3.7 is EOL, maybe. Or we could use `tokenize` on Python 3.7 (we already do to get the ending line numbers). It's honestly not a priority to me, because I use type annotations, but if someone wants to send a PR to Griffe, I'll review it.

How do you add a comment/docstring to a constant? I have seen docstrings below the constant declaration as a workaround but that seems odd to me.

**Comment by pawamoy** [comment]
It's not a workaround, it's the official, supported way :slightly_smiling_face: 
I believe Sphinx (and utils) supports docstrings below assignments as well, and since we write docstrings below classes and functions declarations (well, within the body), I think it's pretty consistent!

**Comment by johnthagen** [comment]
Attribute docstrings are officially documented in the docstring PEP: https://peps.python.org/pep-0257/#what-is-a-docstring

> String literals occurring immediately after a simple assignment at the top level of a module, class, or __init__ method are called “attribute docstrings”.

**Comment by pawamoy** [comment]
OK so since the old handler is destined to be deprecated, and the new one doesn't suffer from the original issue reported here. I'll close this. I'll work on a Django extension for the new handler very soon :slightly_smiling_face:
